# -*- coding: utf-8 -*-
"""Data Science Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzUFF8iRQeFFhqy45iOusPo-F5umHvGn
"""

import pandas as pd
import numpy as np

PPfrom google.colab import files
uploaded = files.upload()

df = pd.read_csv("student_exam_scores.csv")
df.head()

data = df.to_numpy()
print(data)

marks = df['exam_score'].to_numpy()
print(marks)

avg_marks = np.mean(marks)
print("Average Marks:", avg_marks)

max_marks = np.max(marks)
print("Highest Marks:", max_marks)

min_marks = np.min(marks)
print("Lowest Marks:", min_marks)

total_marks = np.sum(marks)
print("Total Marks:", total_marks)

failed = marks < 35
print("Failed Students (True = Fail):", failed)

pass_count = np.sum(marks >= 35)
fail_count = np.sum(marks < 35)

print("Pass Students:", pass_count)
print("Fail Students:", fail_count)

topper_index = np.argmax(marks)
topper = df.iloc[topper_index]

print("Topper Details:")
print(topper)

df['Result'] = np.where(df['exam_score'] >= 35, 'Pass', 'Fail')
df.head()

df.to_csv("final_result.csv", index=False)

# Students scoring above average
above_avg = marks > avg_marks
print("Students above average:", np.sum(above_avg))